-- Innov8IT workspace database schema for Supabase PostgreSQL.
-- Run this in Supabase SQL Editor.
-- The application currently uses Prisma for server-side database access.

create extension if not exists pgcrypto;

create table if not exists public."Workspace" (
  "id" text primary key,
  "name" text not null,
  "image" text,
  "ownerId" text not null
);

create table if not exists public."Channel" (
  "id" text primary key,
  "name" text not null,
  "description" text,
  "memberIds" jsonb,
  "workspaceId" text not null references public."Workspace"("id") on delete cascade
);

create table if not exists public."Membership" (
  "id" text primary key,
  "userId" text not null,
  "email" text not null,
  "workspaceId" text not null references public."Workspace"("id") on delete cascade,
  "role" text default 'member',
  "joinedAt" timestamptz default now(),
  constraint "Membership_userId_workspaceId_key" unique ("userId", "workspaceId")
);

create table if not exists public."Invitation" (
  "id" integer generated by default as identity primary key,
  "email" text not null,
  "token" text not null unique,
  "workspaceId" text not null references public."Workspace"("id") on delete cascade,
  "invitedById" text not null,
  "acceptedById" text,
  "createdAt" timestamptz not null default now(),
  "acceptedAt" timestamptz
);

create index if not exists "Channel_workspaceId_idx"
  on public."Channel" ("workspaceId");

create index if not exists "Membership_workspaceId_idx"
  on public."Membership" ("workspaceId");

create index if not exists "Invitation_workspaceId_idx"
  on public."Invitation" ("workspaceId");

-- The current application authenticates with Clerk and accesses this schema
-- through Prisma on the server. Do not expose the database connection string
-- or service credentials in browser-side environment variables.
